namespace GrapesJsEditorHtml.ViewModel
{
  public class ParametrageListe
  {
    public static List<string> excludecompte = new List<string> { "Personne.Accreditation.Film.Ecole", "Personne.Accreditation.Film.SocieteProd", "Personne.Accreditation.Societe.Selectionneur" };
    public static List<string> excludeaccred = new List<string> { "Accreditation.Film.SocieteProd.Selectionneur", "Accreditation.Film.Ecole.Selectionneur", "Accreditation.Film.Ecole.DetailPays", "Accreditation.Societe.Selectionneur.Accreditation" };
    public static List<string> excludesoc = new List<string> { "Selectionneur.Accreditation.Film.Ecole.Selectionneur", "Selectionneur.Accreditation.Film.Ecole", "Selectionneur.Accreditation.Film.SocieteProd.Selectionneur", "Selectionneur.Accreditation.Film.SocieteProd", "Selectionneur.Accreditation.Film.SocieteProd.Selectionneur.Accreditation", "Selectionneur.Accreditation.Societe.Selectionneur" };
    public static List<string> excludedem = new List<string> {"Billets","Film.Ecole.CompteCreateur","Film.SocieteProd.CompteCreateur","Projection.Film.Ecole.CompteCreateur", "Projection.Film.SocieteProd.CompteCreateur", "Projection.Film.SocieteProd.Selectionneur", "Projection.Film.Ecole.Selectionneur","Film.Ecole.Selectionneur.Accreditation","Film.SocieteProd.Selectionneur.Accreditation","Film.Societe.Selectionneur.Accreditation",
            "Personne.Accreditation.Film.Ecole", "Personne.Accreditation.Film.Societe", "Personne.Accreditation.Film.SocieteProd","Personne.Accreditation.Societe.Selectionneur",
          "Accreditation.Film.Ecole","Accreditation.Film.SocieteProd.CompteCreateur","Accreditation.Film.Societe.CompteCreateur","Accreditation.Film.SocieteProd.CompteCreateur","Accreditation.Film.Societe.CompteCreateur","Accreditation.Societe.Selectionneur","Accreditation.Societe.CompteCreateur"
          ,"Accreditation.Film.SocieteProd.Selectionneur","Projection.Film.SocieteProd.DetailPays","Projection.Film.Ecole.DetailPays","Accreditation.Film.SocieteProd","Projection.Film.Societe.DetailPays","Projection.Accreditation","Projection.Personne","Projection.Societe","Projection.Ecole","Projection.SocieteProd","Projection.Selectionneur","Projection.CompteCreateur"};
    public static List<string> excludeope = new List<string> { "Societe.Selectionneur.Accreditation.Film", "Societe.Selectionneur.Accreditation.Emetteur", "Societe.Selectionneur.Accreditation.Societe", "Societe.Selectionneur.Accreditation.Contingent", "Societe.Selectionneur.Accreditation.StatutDetail" };
    public static List<string> excludecom = new List<string> { "Operation.Societe.Selectionneur.Accreditation", "Contact.Accreditation.Film.Ecole", "Contact.Accreditation.Societe.Selectionneur", "Contact.Accreditation.Societe.SocieteProd", "Contact.Accreditation.Film.Ecole.SocieteProd", "Contact.Accreditation.Film.SocieteProd" , "Contact2.Accreditation.Societe.Selectionneur", "Contact2.Accreditation.Societe.SocieteProd", "Contact2.Accreditation.Film.Societe.Selectionneur", "Contact2.Accreditation.Film.Ecole", "Contact2.Accreditation.Film.SocieteProd",
          "OperationFacture.Societe.Selectionneur.Accreditation","Contact.Accreditation.Film.SocieteProd","Societe.Selectionneur.Accreditation.Film","Societe.Selectionneur.Accreditation.Societe","Societe.Selectionneur.Accreditation.Emetteur","Societe.Selectionneur.Accreditation.Contingent","Societe.Selectionneur.Accreditation.StatutDetail","Societe.Selectionneur.Accreditation.Statut","SocieteDecoratrice.Selectionneur.Accreditation.Film","SocieteDecoratrice.Selectionneur.Accreditation.Societe","SocieteDecoratrice.Selectionneur.Accreditation.Emetteur","SocieteDecoratrice.Selectionneur.Accreditation.Contingent",
            "SocieteDecoratrice.Selectionneur.Accreditation.StatutDetail", "SocieteDecoratrice.Selectionneur.Accreditation.Statut"};
    public static List<string> excludeinsc = new List<string> { "Film.Ecole.Selectionneur.Accreditation", "Film.SocieteProd.Selectionneur.Accreditation" };
    public static List<string> excludeproj = new List<string> { "Film.Societe.Selectionneur.Accreditation", "Societe.Selectionneur.Accreditation.Contingent", "Societe.Selectionneur.Accreditation.Emetteur", "Societe.Selectionneur.Accreditation.Film", "Societe.Selectionneur.Accreditation.Societe", "Societe.Selectionneur.Accreditation.StatutDetail", "Societe.Selectionneur.Accreditation.StatutDetail", "Societe.Selectionneur.Accreditation.Statut" };
    public static List<string> excludebcd = new List<string> { "Operation.Societe.Selectionneur.Accreditation", "Societe.Selectionneur.Accreditation.Emetteur", "Societe.Selectionneur.Accreditation.Film", "Societe.Selectionneur.Accreditation.Contingent", "Societe.Selectionneur.Accreditation.Societe", "Societe.Selectionneur.Accreditation.Statut", "Societe.Selectionneur.Accreditation" };
    public static List<string> excludebil = new List<string> { "Billets", "Accreditation.Film.Ecole.CompteCreateur", "Accreditation.Film.Ecole", "Accreditation.Film.SocieteProd", "Accreditation.Societe.Selectionneur", "Accreditation.Societe.CompteCreateur", "Projection.Film.Ecole.Selectionneur", "Projection.Film.Ecole.CompteCreateur", "Projection.Film.SocieteProd.Selectionneur", "Projection.Film.SocieteProd.CompteCreateur" };
    public static List<string> excludersdata = new List<string> { "Realisateur.Accreditation.Film.Ecole", "Realisateur.Accreditation.Film.SocieteProd", "Realisateur.Accreditation.Societe.Selectionneur" };
  }
}
